//this file sample replaces the ./src/auth-config.js to load config for this provider
//this configuration is generated by the auth provider backend implementation
//and is stored as an output on the serverless-saas CloudFormation stack
const auth_config = {
  "idp": {
    "name": "Auth0",
    "domain": "",
    "clientId": ""
  }
}
export default auth_config;
